#!/bin/bash

NAME=$1
PW=$2

# Generate keypair
openssl req -nodes -new -x509 \
-days 365 -sha256 -newkey rsa:2048 \
-keyout $NAME.key \
-out $NAME.crt \
-subj /CN=$NAME/OU=$NAME

# Combine into PFX
openssl pkcs12 -export -passout pass:$PW \
-in $NAME.crt \
-inkey $NAME.key \
-certfile $NAME.crt \
-out $NAME.p12
